---
name: Run Fuzzing Tests

on: [push]
jobs:
  fuzzing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20'
          cache: false
      - name: Fuzzing Test
        run: |
          go test -fuzz Fuzz -fuzztime 10s  ./pkg/db
